title = "Sanford Tutoring"

baseURL = "https://sanfordtutoring.com/"
languageCode = "en-us"
disableKinds = ["taxonomy"]
enableRobotsTXT = true

# The site's parameters
[params]
  dateFormat = "6 January 2006"
  home = "Home"
  description = "Certified math teacher offers personalized 1-on-1 instruction for homeschoolers in pre-algebra and beyond, available both online and in person."
  images = [
    "images/hero-a-1110x555.jpg"
  ]
  [params.firebase]
    projectId = "sanford-tutoring"
    apiKey = "AIzaSyCj4vR88yJH7OY13TiBuXM5soiHmdAv3IE"
    appId = "1:93390974990:web:7def7e575a110c5a"

  [params.localBusiness]
    image = "images/hero-a-1110x555.jpg"
    name = "Sanford Tutoring"
    telephone = "+15616541889"
    priceRange = "$0-75/hr"
    [params.localBusiness.address]
      "streetAddress"= "5054 Knotty Pine Ct"
      "locality" = "Sanford"
      "region" = "FL"
      "postalCode" = "32771"
      "country" = "US"
    [params.localBusiness.geo]
      "latitude" = 28.7776532
      "longitude" = -81.4147597
    
[social]
  # twitter = 

[build]
  [build.buildStats]
    enable = true

[module]
  [[module.mounts]]
    # Workaround for https://github.com/gohugoio/hugo/issues/6945
    source = "assets/scss/bootstrap/_vendor"
    target = "assets/scss/bootstrap/vendor"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = 'node_modules/bootstrap/scss'
    target = 'assets/scss/bootstrap'
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"